import About from './About'
import Hero from './Hero'
import Nav from './nav'
import Footer from './footer'
import Services from './services'
import FAQs from './FAQs'
import Number from './Number'
import Team from './Team'
import Project from './projects'
import Wedo from './we_do'
import ClientSlider from './weareworkingwith'
import Path from './path'
import LoginPage from './Login'
import Contact from './Contact'
import RegistrationPage from './register'
import MouseFollow from './mouseFollower'
import PageNotFound from './PageNotFound'
import ResetPassword from './resetpassword'

export {About,Hero,Nav,FAQs,Footer,Number,Team,Project,Wedo,Services,ClientSlider,Path,LoginPage,Contact,RegistrationPage,PageNotFound,MouseFollow,ResetPassword} 